/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_administrator_mcpttclient_SipJNI */

#ifndef _Included_com_example_administrator_mcpttclient_SipJNI
#define _Included_com_example_administrator_mcpttclient_SipJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_administrator_mcpttclient_SipJNI
 * Method:    RegistJavaClassToJni
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_administrator_mcpttclient_SipJNI_RegistJavaClassToJni
  (JNIEnv *, jclass);

/*
 * Class:     com_example_administrator_mcpttclient_SipJNI
 * Method:    Request_from_UI_with_ByeArray
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_example_administrator_mcpttclient_SipJNI_Request_1from_1UI_1with_1ByeArray
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
